using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Chapter_4___Exception_Handling
{
    internal class Can_we_execute_multiple_catch_block
    {
   //     static void Main(string[] args)
   //     {
			//try
			//{
			//	int i = 0;
			//	int j = 0;

			//	int k = i / j;
			//}
			//catch (ArithmeticException ex )
			//{
			//	Console.WriteLine(ex.Message);
			//	//throw;
			//}
			//catch (Exception ex)
			//{
			//	Console.WriteLine(ex.Message);
			//}
   //     }
    }
}
